### ISSUE TITLE
Add base Code

### ISSUE THREAD

**Issue by alagbesola** [oyekanmijr/Nacbams#1]
Please let's use this medium to collaborate.
![word](https://user-images.githubusercontent.com/32680305/40012589-0a5de294-57a3-11e8-9aac-9ae31066c487.jpg)

**Comment by Uchman84** [comment]
See you Brov, Let get...............................................

**Comment by oyekanmijr** [comment]
![about us- how we change the world](https://user-images.githubusercontent.com/38434490/40042002-c6b0bbaa-5817-11e8-9f38-396722a37f31.jpg)
![about us- our vision](https://user-images.githubusercontent.com/38434490/40042006-c706c766-5817-11e8-87b6-bc3dfe8af1ab.jpg)
![hamburger1](https://user-images.githubusercontent.com/38434490/40042007-c74aae54-5817-11e8-9c9a-f8b949dc68f0.jpg)
![home page](https://user-images.githubusercontent.com/38434490/40042008-c775b4c8-5817-11e8-9029-19616765887f.jpg)
![news and opportunities](https://user-images.githubusercontent.com/38434490/40042009-c79e6882-5817-11e8-9472-e8b18c1f0040.jpg)
![our chapters](https://user-images.githubusercontent.com/38434490/40042010-c7d5d588-5817-11e8-9523-94b0680cb0f6.jpg)
![about us- our history](https://user-images.githubusercontent.com/38434490/40042343-eab70486-5818-11e8-851e-2129a6a4d7c3.jpg)

**Comment by oyekanmijr** [comment]
Hi guys, I have uploaded the designs. I am still working on the others but please let us start work on this one and let us have a shareable link for it so other memebrs of the association will be able to view the work as it progresses. 
Cheers!
